appVersion: latest
image:
  app: ghcr.io/tim-hat-die-hand-an-der-maus/api

postgres:
  db: tim
  user: tim
  host: tim-db-rw

sentry:
  dsn: ${SENTRY_DSN}

api:
  replicas: 2

ingress:
  hosts:
    - tim-api.bembel.party
    - tim-api-local.bembel.party

cronJobs:
  - name: full-metadata-update
    schedule: "* * * * *"
    args: [ "update-metadata" ]
    suspend: true
  - name: metadata-refresh
    schedule: "42 4 * * *"
    args: [ "update-metadata", "--min-age=14", "--limit=30" ]
  - name: shuffle-queue
    schedule: "0 6 * * 1"
    backoffLimit: 3
    args: [ "shuffle-queue" ]
