appVersion: latest
image:
  app: ghcr.io/tim-hat-die-hand-an-der-maus/api

postgres:
  db: tim
  user: tim
  host: tim-db-rw

sentry:
  dsn: ${SENTRY_DSN}

api:
  replicas: 3

ingress:
  hosts:
    - tim-api.bembel.party
    - tim-api-local.bembel.party
