volumes:
  db: {}

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tim
      POSTGRES_USER: tim
      POSTGRES_PASSWORD: pw
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready
