apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  annotations:
    cert-manager.io/cluster-issuer: zerossl
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-rotation-policy: Always
    cert-manager.io/issue-temporary-certificate: "false"
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  name: http
            path: /
            pathType: Prefix
    {{- end }}
  tls:
    - hosts: {{ .Values.ingress.hosts | toJson }}
      secretName: tls-api
