---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  refreshInterval: "24h"
  secretStoreRef:
    name: scaleway-tim-api
    kind: ClusterSecretStore
  data:
    - remoteRef:
        key: "name:sentry-dsn"
      secretKey: QUARKUS_LOG_SENTRY_DSN
