---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  secretStoreRef:
    name: doppler-tim
    kind: ClusterSecretStore
  target:
    name: api-secrets
  data:
    - remoteRef:
        key: API_SENTRY_DSN
      secretKey: QUARKUS_LOG_SENTRY_DSN
