---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-secrets
spec:
  secretStoreRef:
    name: scaleway-tim-api
    kind: ClusterSecretStore
  target:
    name: api-secrets
  data:
    - remoteRef:
        key: "name:sentry-dsn"
      secretKey: QUARKUS_LOG_SENTRY_DSN
