{{- range .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .name }}
spec:
  schedule: {{ .schedule | quote }}
  timeZone: "Europe/Berlin"
  suspend: {{ .suspend | default false }}
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          containers:
            - name: app
              image: {{ $.Values.image.app }}:{{ $.Values.appVersion }}
              args: {{ .args | toJson }}
              resources:
                requests:
                  cpu: 500m
                  memory: 128Mi
                limits:
                  cpu: 500m
              envFrom:
                - configMapRef:
                    name: api-db-config
                - configMapRef:
                    name: api-service-config
                - secretRef:
                    name: api-secrets
                - secretRef:
                    name: api-db-secrets
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
{{- end }}
