---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: shuffle-queue
spec:
  schedule: "0 6 * * 1"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 1
  startingDeadlineSeconds: 1200
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            seccompProfile:
              type: RuntimeDefault
          restartPolicy: Never
          containers:
            - name: app
              image: {{ .Values.image.app }}:{{ .Values.appVersion }}
              args:
                - shuffle-queue
              resources:
                limits:
                  cpu: 100m
                requests:
                  cpu: 100m
                  memory: 128Mi
              envFrom:
                - configMapRef:
                    name: api-db-config
                - configMapRef:
                    name: api-service-config
                - secretRef:
                    name: api-secrets
                - secretRef:
                    name: api-db-secrets
              env:
                - name: QUARKUS_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.user }}.{{ .Values.postgres.host }}.credentials.postgresql.acid.zalan.do
                      key: password
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
