kind: ConfigMap
apiVersion: v1
metadata:
  name: api-db-config
data:
  QUARKUS_DATASOURCE_HOST: {{ .Values.postgres.host }}
  QUARKUS_DATASOURCE_USER: {{ .Values.postgres.user }}
  QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://{{ .Values.postgres.host }}:5432/{{ .Values.postgres.db }}"
