---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: app
          image: {{ .Values.image }}
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              port: 8080
              path: /q/health/live
          readinessProbe:
            httpGet:
              port: 8080
              path: /q/health/ready
          resources:
            limits:
              cpu: 100m
            requests:
              cpu: 30m
              memory: 64Mi
          envFrom:
            - configMapRef:
                name: api-db-config
            - configMapRef:
                name: api-service-config
            - secretRef:
                name: api-secrets
          env:
            - name: QUARKUS_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.user }}.{{ .Values.postgres.host }}.credentials.postgresql.acid.zalan.do
                  key: password
