apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ .Values.postgres.host }}
spec:
  teamId: "tim"
  volume:
    size: 1Gi
  numberOfInstances: 3
  users:
    {{ .Values.postgres.user }}: []
  databases:
    {{ .Values.postgres.db }}: {{ .Values.postgres.user }}
  postgresql:
    version: "14"
    parameters:
      password_encryption: scram-sha-256
