---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: full-metadata-update
  labels:
    app: full-metadata-update
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 3
  startingDeadlineSeconds: 1200
  suspend: true
  jobTemplate:
    metadata:
      labels:
        app: full-metadata-update
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: app
              image: {{ .Values.image }}
              args:
                - update-metadata
              resources:
                limits:
                  cpu: 100m
                requests:
                  cpu: 50m
                  memory: 128Mi
              envFrom:
                - configMapRef:
                    name: api-db-config
                - configMapRef:
                    name: api-service-config
                - secretRef:
                    name: api-secrets
              env:
                - name: QUARKUS_DATASOURCE_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Values.postgres.user }}.{{ .Values.postgres.host }}.credentials.postgresql.acid.zalan.do
                      key: password
