---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: {{ .Values.postgres.db }}
  POSTGRES_HOSTNAME: {{ .Values.postgres.host }}
  POSTGRES_USER: {{ .Values.postgres.user }}
  PGDATA: /data/pg
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-data
      containers:
        - name: postgres
          image: postgres:14-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          volumeMounts:
            - mountPath: /data
              name: data
          envFrom:
            - secretRef:
                name: postgres-secrets
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.host }}
spec:
  ports:
    - name: psql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: postgres
