name: Main
on: push

jobs:
  check:
    name: Test and Lint
    runs-on: ubuntu-latest
    container: openjdk:11-jdk
    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_DB: tim
          POSTGRES_USER: tim
          POSTGRES_PASSWORD: pw
    env:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/tim"
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run checks
        run: ./gradlew check

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/main'
    needs:
      - check
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the tagged Docker image
        run: docker build -t ghcr.io/tim-hat-die-hand-an-der-maus/api:${GITHUB_SHA} --build-arg "build=${GITHUB_SHA}" .
      - name: Push the tagged Docker image
        run: docker push ghcr.io/tim-hat-die-hand-an-der-maus/api:${GITHUB_SHA}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: docker
    env:
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Substitute environment variables in values.yaml
        run: "envsubst < values.yaml > values_sub.yaml && mv values_sub.yaml values.yaml"
      - name: Deploy helm chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm upgrade backend . --install --namespace=timhatdiehandandermaus
          kubeconfig: '${{ secrets.KUBECONFIG_RAW }}'
