name: Main
on:
  push:
    branches: [ main ]
  pull_request: {}

jobs:
  required-meta:
    permissions:
      contents: read
      pull-requests: write
      checks: write
    uses: BlindfoldedSurgery/actions-meta/.github/workflows/required.yml@v1

  check:
    name: Test and Lint
    runs-on: ubuntu-24.04
    container: eclipse-temurin:21
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: tim
          POSTGRES_USER: tim
          POSTGRES_PASSWORD: pw
    env:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/tim"
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Run checks
        run: ./mvnw --no-transfer-progress spotless:check test

  build-container-image:
    needs:
      - check
    uses: tim-hat-die-hand-an-der-maus/actions-container/.github/workflows/build-dual-image-kaniko.yml@v6
    with:
      amd-runner-name: warp-ubuntu-latest-x64-8x
      arm-runner-name: warp-ubuntu-latest-arm64-8x
      push-image: ${{ github.ref_name == github.event.repository.default_branch }}

  post-build-container-image:
    name: Container Build
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    needs: build-container-image
    steps:
      - run: echo "All images built"

  deploy:
    runs-on: ubuntu-24.04
    if: github.ref_name == github.event.repository.default_branch
    permissions:
      contents: write
    needs:
      - build-container-image
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git push origin main:release

  clean:
    concurrency: cleanup
    needs: [ deploy ]
    uses: tim-hat-die-hand-an-der-maus/actions-container/.github/workflows/clean.yml@v6
